# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jsaper
email: martinkro@aliyun.com
description: >- # this means to ignore newlines until "baseurl:"
  Focus on computer tech such as machine learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  martinkro

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: true
#markdown: redcarpet
#redcarpet:
#  hard_wrap: true
#  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
# theme: minima
# theme: midnight
# theme: modernist
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /articles/:year/:month/:day/:title
paginate: 8
paginate_path: "articles/page:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: UA-86517450-2
